name: Robot Framework

on:
  push:
    branches:
    - main
    - backed-tests

jobs:
  robot_test:
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create folder for reports
        run: mkdir reports
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v1.0
        with:
          robot_tests_dir: 'tests'
      - name: Upload reports
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          # set path to Robot Framework results reports. Exclude dummy file that is needed because of ppodgorsek image priviledges.
          path: ${{ github.workspace }}/reports
