name: Robot Framework

on:
  push:
    branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
        name: Run Robot Framework Tests
        steps:
          - uses: actions/checkout@v2
          - name: Execute tests
            uses: joonvena/robotframework-docker-action@v1.0
            with:
              ROBOT_TESTS_DIR: $GITHUB_WORKSPACE/tests
